name: Update data

on:
  schedule:
    - cron: "45 9 * * *"  # 16:45 (4:45 PM) in Vietnam - For XSMN
    - cron: "45 10 * * *" # 17:45 (5:45 PM) in Vietnam - For XSMT
    - cron: "45 11 * * *" # 18:45 (6:45 PM) in Vietnam - For XSMB
  workflow_dispatch: # Allow manual trigger

env:
  TZ: "Asia/Ho_Chi_Minh" # Set timezone to Vietnam

jobs:
  update-data:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Grant write permission to GITHUB_TOKEN
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to ensure proper updates

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: install python packages
        run: pip install -r requirements.txt

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Debug - Print Pydantic version
        run: pip show pydantic

      - name: Fetch Lottery Data
        run: |
          if [ "${{ github.event.schedule }}" == "45 9 * * *" ]; then
            echo "Fetching Southern region (XSMN) data"
            python -m src.fetch --end ${{ env.date }} --region MN
          elif [ "${{ github.event.schedule }}" == "45 10 * * *" ]; then
            echo "Fetching Central region (XSMT) data"
            python -m src.fetch --end ${{ env.date }} --region MT
          elif [ "${{ github.event.schedule }}" == "45 11 * * *" ]; then
            echo "Fetching Northern region (XSMB) data"
            python -m src.fetch --end ${{ env.date }} --region MB
          else
            echo "Manual run or unknown schedule, fetching all regions"
            python -m src.fetch --end ${{ env.date }}
          fi

      - name: Generate lottery predictions
        run: python src/lottery_analyzer.py

      - name: push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          message: "Automated data update for Vietnam Lottery - ${{ env.date }}"
          email: action@github.com
          name: GitHub Action